(Draft / feedback required) Build the client as an app bundle on macOS
Net5F/Repose pull request #2
Opened 2023-03-08 02:56 UTC by NeRdTheNed

Current issues:
- The app bundle won't work until after it's been packaged, as that's when the resources are copied into it.
- There seems to be a large amount of bundled libraries, I'm not sure they're all needed.
- The app might try to write to folders inside of the app bundle (for logging), which is not allowed by macOS due to app signing. The user might also want to modify the user config file, but that's also packaged inside of the app bundle folder, so modifying it is also not allowed.
  - A better solution might be to re-write code to use `~/Library/Application Support/Repose/` for these files.
  - Related: the #ifdef \_\_APPLE\_\_ I added is not a good solution to finding the client config file.

2023-03-08 04:59 UTC, Net5F commented
> The app bundle won't work until after it's been packaged, as that's when the resources are copied into it.

I'm not super familiar with app bundles, are you saying the bundle is created by the configure/build steps and the binary is put there, but we don't copy the resources until the packaging step? If that's the case and we want it to be runnable, could we copy the resources into the bundle during the configure step, similar to how we put them next to the binary here? https://github.com/Net5F/Repose/blob/be153aa5bf75ef6568b4598d5230cef0d7fa9dd4/Source/Client/CMakeLists.txt#L30

> There seems to be a large amount of bundled libraries, I'm not sure they're all needed. I've used fixup_bundle from CMake's BundleUtilities to bundle every used library, there's probably a more efficient way to do this.

I used to auto-detect it like this for windows/linux, but I had the same problem. We should only need the various SDL2 modules and their included libs.  Maybe we can just use the paths that the find files give us (like `SDL2_LIBRARY`) and copy those into the bundle? That's pretty close to what we do for windows.

> The app might try to write to folders inside of the app bundle... A better solution might be to re-write code to use ~/Library/Application Support/Repose/ for these files.

I remember seeing SDL2 had a function for this, here it is https://wiki.libsdl.org/SDL2/SDL_GetPrefPath

I could imagine adding a `USER_PREFS_DIR` to [the Paths class](https://github.com/Net5F/AmalgamEngine/blob/master/Source/SharedLib/Utility/Public/Paths.h) and setting it equal to GetPrefPath on all platforms. That would be fine for the log file, but we don't have an installer to put the initial config file there. 

One option for that would be to move the config json to a string in a header file. Then we'd add logic to UserConfig to check if USER_PREFS_DIR/UserConfig.json exists, and if not, create it using the string from the header. That'd be a bit more confusing to people trying to maintain the file, but it isn't that much worse. And it won't be any worse for the eventual end user, since the client will have a settings menu. Maybe there's a better approach, though.

> Without signing the app bundle with an Apple developer ID, anyone who downloads the app is forced to go through several menus / use various key combinations while opening it to run it.

I can pay for an apple dev account for the github actions build. Apple account settings and such confuse me so I wouldn't look forward to maintaining it, but it's doable😅 I would want to wait on this until we're a bit further along and we have non-dev mac users interested in it, though.

2023-03-08 07:12 UTC, NeRdTheNed commented
> I'm not super familiar with app bundles, are you saying the bundle is created by the configure/build steps and the binary is put there, but we don't copy the resources until the packaging step? If that's the case and we want it to be runnable, could we copy the resources into the bundle during the configure step, similar to how we put them next to the binary here?

Fixed!

> I used to auto-detect it like this for windows/linux, but I had the same problem. We should only need the various SDL2 modules and their included libs. Maybe we can just use the paths that the find files give us (like `SDL2_LIBRARY`) and copy those into the bundle? That's pretty close to what we do for windows.

I was mostly surprised at the amount of libraries being pulled in, but after inspecting the bundle with [Apparency](https://www.mothersruin.com/software/Apparency/), I think they're all used. SDL_image is responsible for pulling in a fair amount of image libraries. Because AmalgamEngine is currently built with GCC, we also have to pull in some GCC / C++ runtime libraries that wouldn't usually be required when building with Clang.

> I could imagine adding a `USER_PREFS_DIR` to [the Paths class](https://github.com/Net5F/AmalgamEngine/blob/master/Source/SharedLib/Utility/Public/Paths.h?rgh-link-date=2023-03-08T04%3A59%3A32Z) and setting it equal to GetPrefPath on all platforms. That would be fine for the log file, but we don't have an installer to put the initial config file there.
> 
> One option for that would be to move the config json to a string in a header file. Then we'd add logic to UserConfig to check if USER_PREFS_DIR/UserConfig.json exists, and if not, create it using the string from the header. That'd be a bit more confusing to people trying to maintain the file, but it isn't that much worse. And it won't be any worse for the eventual end user, since the client will have a settings menu. Maybe there's a better approach, though.

I might leave this as a future feature for now, I'm currently the only person using this on MacOS anyway so it's not a huge deal.

> I can pay for an apple dev account for the github actions build. Apple account settings and such confuse me so I wouldn't look forward to maintaining it, but it's doable😅 I would want to wait on this until we're a bit further along and we have non-dev mac users interested in it, though.

I wish Apple hadn't forced developers to pay to sign apps, I completely sympathise with you. I wish I had my own developer ID!

2023-03-08 10:24 UTC, NeRdTheNed commented
I've managed to get Repose to build on MacOS 10.14 with this PR ([app download](https://github.com/Net5F/Repose/files/10919541/Repose.app.10.14.zip)). The build seems to work fine on both the original Intel MacBook running MacOS 10.14 and a M1 MacBook running MacOS 12, which gives me confidence that the bundled libraries work.

2023-03-09 05:21 UTC, Net5F requested changes
Looks great, just a couple small things and we'll be good to merge. I'll add tickets for the future work.

2023-03-09 05:21 UTC, Net5F commented on Source/Client/Config/Private/ProjectUserConfig.cpp
> +#ifdef __APPLE__
Could you add a TODO here? Something like:
```
// TODO: When the engine gets a Paths::USER_PREF_DIR, remove this ifdef and use that.
```

2023-03-09 05:21 UTC, Net5F commented on Source/Client/CMakeLists.txt
> +    target_link_options(
I don't have much of a preference, but just for consistency with the rest of the file, can you put `Client` on the same line as the command? Like:
```
target_link_options(Client
```

2023-03-09 05:21 UTC, Net5F commented on Source/Client/CMakeLists.txt
> +    set_target_properties(
Same here as above
```
set_target_properties(Client
```

2023-03-09 05:21 UTC, Net5F commented on Source/Client/CMakeLists.txt
> +    set(PROJECT_CREATOR_NAME "Net5F")
```suggestion
    set(PROJECT_CREATOR_NAME "Net_")
```
I couldn't get my usual name on github, but I like the underscore 😅

2023-03-09 05:21 UTC, Net5F commented on Resources/Client/macOS/README.txt
> +Code by Net_
Feel free to add a "macOS build originally by " here, if you'd like 😄 Up to you, you might want to avoid people looking you up if something breaks 😅

2023-03-10 22:30 UTC, NeRdTheNed commented on Source/Client/Config/Private/ProjectUserConfig.cpp
> +#ifdef __APPLE__
Added!

2023-03-10 22:35 UTC, NeRdTheNed commented
@Net5F Sorry for not addressing this feedback until now, I think everything should be resolved!

2023-03-11 07:50 UTC, Net5F approved these changes
Looks great, thanks again 😄

2023-03-11 07:50 UTC, merged